### ISSUE TITLE
How to add UIKit Element ? (tab)

### ISSUE THREAD

**Issue by Mat2012** [Getbeans/Beans#18]
Hello, 
Thanks for your brilliant work! Beans is a very cool framework, I'm currently testing it.
I try to add a component of the UIKit in the theme : the tab component.
(http://getuikit.com/docs/tab.html)

So, in my functions.php, I have added theses lines of code in order to register this component and its dependancies 
```
add_action( 'beans_uikit_enqueue_scripts', 'my_function_name' );
function my_function_name() {
	beans_uikit_enqueue_components( array( 'dropdown, toggle, switcher, tab' ) );
}
```
Then, in a post, I have added these HTML classes 
```
<ul class="uk-tab" data-uk-tab>
    <li class="uk-active"><a href="">hhhh</a></li>
    <li><a href="">dfghjk</a></li>
    <li><a href="">oiuytr</a></li>
    <li class="uk-disabled"><a href="">hhhh</a></li>
</ul>
```
But it doesn't work, the tabs don't appear. 
What did I miss ?

Thanks !

**Comment by ThierryA** [comment]
Hi @Mat2012 ,

Thanks for your kind words :) Your PHP array format isn't quite correct. Change it to the following:

`beans_uikit_enqueue_components( array( 'dropdown', 'toggle', 'switcher', 'tab' ) );`

FYI, sometimes loading components can be a bit tricky like for the tab for example, the switcher is needed which you correctly included in this case. If you ever scratch your head, you can run the code below to load the entire library in order to test if the issue could be that you are missing a component.

```
beans_uikit_enqueue_components( true );
beans_uikit_enqueue_components( true, 'add-ons' );
```
Hope that helps, happy coding,

**Comment by Mat2012** [comment]
Oh ! My mistake... Thank you for your quick response, and for the tips. It works.
Have a nice day !

**Comment by ThierryA** [comment]
It is a pleasure :)
