### ISSUE TITLE
Post gallery: images not resized using the Image API

### ISSUE THREAD

**Issue by devignerforhire** [Getbeans/Beans#23]
I tested changing the gallery image size from medium, thumbnail, etc but all of them output the full image (in this case 2048). When set to the thumbnail option, the width and height attributes are added to the image, but the image used is still the original. I initially thought this was because I had no defaults set in the media settings (to prevent WP from creating additional images), but I tested setting the media defaults in the settings, recreated the gallery and the result was the same. The only difference is the width from the settings was used.

**Comment by ThierryA** [comment]
Hey @devignerforhire, the image size is controlled by WP media for the gallery and not Beans API.

That said you are welcome to use the `beans_post_gallery_icon[_{$attachment_id}]_output` filter to write your own. You have access to `$image_output, $attachment_id, $atts` parameters in the callback functions so you really have everything you need to use the Beans Image API :-)

FYI, the images sizes won't be control using the Beans Image API in Beans core because it depends to much on the columns and where it is used.
