### ISSUE TITLE
How to contribute to the website?

### ISSUE THREAD

**Issue by ibes** [Getbeans/Beans#325]
title says it all.

- I would like to be able to propose code snippets
- I wanted to check the documentation about the new helper functions that arrived with 1.5.0 and I am quite sure they are not yet documented - so I feel like that could be a thing to add.

There are two empty repos in the Getbeans organisation. 

What would be needed to put the website in a repository?
Or is there another good way. 

I guess having the website on github could help to extend the website. 

Also @hellofromtonya put the idea out that there could/should/will be a blog on the website. 
Any updates on that. 
There is an article of me ready to be reviewed about how to get Beans working with Composer.

(by the way: I am now really starting to use Beans and looking forward to further contribute)

**Comment by paaljoachim** [comment]
Hey Ibes

I believe the best way to contribute to Beans is by creating tutorials, and in general sharing useful information of things we learn. I do this with wpbeansframework.com. I sent you an e-mail and it would be great if we can work a bit together on creating tutorials/documentation that I for now anyway can add to the tutorial site I have. We can later on take content from it and add it to the new get beans web site. The main point for me is to learn as much as I can, take content from the forums, test it out and then create tutorials.

Regarding the two empty repos:
It would be good to have the existing site added here by anyone that has the access to do so.
https://github.com/Getbeans/getbeansio

The new site repo:
https://github.com/Getbeans/Website

As I have been involved with Beans since sometime in I believe 2015 I have noticed that there are long periods of non activity. Very quiet. Earlier I had to constantly go back to using Genesis child themes as I did not have enough tutorials and documentation to create child themes using Beans. These days it is different. I am now finally able to use my own tutorials to create child themes. Questions that come up for me, well I just hope that someone on slack on the forums reply. When there is no reply I find ways to work around it. 

My bottom line is: Lets create documentation/tutorials and find ways to share it with the community.

**Comment by ibes** [comment]
Sounds great. 

Thanks for reaching out - so let's start add to your page and see how soon it will be possible to merge the content into an official thing.

**Comment by christophherr** [comment]
@ibes 
I guess that the documentation parser hasn't been run on the 1.5 code base. Only Tonya or Thierry can do that.

As for the website, try the beans-website Slack channel. 
If I remember correctly, Tonya wanted to get 2.0 into Beta before focusing on website/blog/marketing. 
IMO, worth discussing if we should decouple that.

I'm going to close the issue. 
Please feel free to continue the discussion here or in Slack,

**Comment by ibes** [comment]
I feel like, this shouldn't be closed.

Documentation and tutorials are a major feature in all projects. 
It is the reason why some projects thrive and others fail. 

Beans 2.0 doesn't seem like a thing that will happen in the next two or so month (if there are other information let me know).

I am not talking about marketing - I am talking about developer help and start up help. 

I am happy that @paaljoachim just pragmatically started an own page for that and will contribute there. 
Maybe there is a chance to promote that page through the official resources. 
Again - it's about giving people the chance to have their go with Beans. 

It is already a great tool - even if I am super looking forward to v2.0

**Comment by christophherr** [comment]
Closing an issue doesn't mean the point/question is not important. 
Slack seems to be the better place for a discussion than GH. 
The beans-website Slack channel has the purpose of discussing what is going to happen with the website. Interested people are already subscribed to that channel and probably don't know about the discussion here. 
I'd rather not scatter the topic in different places.

If you want to contribute code snippets for the website, feel free to post them on Slack. 
We have a few people with Editor rights who could possibly add content to the website.

**Comment by paaljoachim** [comment]
Well just like my other web page easywebdesigntutorials.com, wpbeansframework.com is a site I will add various tutorials for my own use and for everyones use. When the time comes I will also help with the documentation and tutorials for the official site. I believe my site is a very good resource that will help a lot of beginners get into Beans. Do remember one thing... I am not a developer. I am a teacher. This means it will take me more time to figure out things, but the flipside to that is that I learn a lot along the way. The more I use Beans the more I will also discover new things along the way.

Btw it is also important to atleast once a week take a look at the forums on the official site and reply to a few of the questions, as the forums is the main place to learn.

Thanks for going through the issues Christoph!
