### ISSUE TITLE
"Next Post" Icon Close Markup ID is Incorrect

### ISSUE THREAD

**Issue by hellofromtonya** [Getbeans/Beans#91]
In the function `beans_next_post_link`, the ID for closing the next icon's markup is incorrect.

The opening markup uses the ID `'beans_next_icon[_post_navigation]'`.  However, the closing markup uses a different ID `'beans_previous_icon[_post_navigation]'`.

**Comment by ThierryA** [comment]
Correct, `beans_previous_icon[_more_link]` should be changed to `beans_next_icon[_more_link]` [here](https://github.com/Getbeans/Beans/blob/development/lib/templates/fragments/post.php#L308) and `beans_previous_icon[_post_navigation]` should be changed to `beans_next_icon[_post_navigation]` [here](https://github.com/Getbeans/Beans/blob/development/lib/templates/fragments/post.php#L432).

We want to keep the first part of the filter the same name (aka `beans_next_icon`) so that we can either target all "next icons" or add more specificity if we want to target either the more link or post navigation.
